apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  initTimeout: 1m
  metadata:
    - name: redisHost
      value: redis-master.dapr-tests.svc:6379
    - name: redisPassword
      value: "Daprio7p"
    - name: actorStateStore
      value: true
scopes:
  - app-consumer
  - app-publisher