apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: app-subscription
spec:
  topic: topic
  route: /consume
  pubsubname: pubsub
scopes:
  - app-consumer
  - app-publisher
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: app-bulk-subscription
spec:
  topic: bulk
  route: /bulk
  pubsubname: pubsub
scopes:
  - app-consumer
  - app-publisher
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: app-raw-subscription

spec:
  topic: raw
  route: /raw
  pubsubname: pubsub
  metadata:
    isRawPayload: "true"
scopes:
  - app-consumer
  - app-publisher
---